name: Carregando credenciais do Google Sheets

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  read-sheet:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gspread oauth2client python-dotenv

      - name: Criar arquivo de credenciais
        run: |
          printf "%s" "$GOOGLE_CREDENTIALS_JSON" > credentials.json
          export GOOGLE_CREDENTIALS_JSON=credentials.json
          python drive.py