name: Atualizar Google Sheet das turmas do Geração Tech

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      SPONTE_EMAIL: ${{ secrets.SPONTE_EMAIL }}
      SPONTE_PASSWORD: ${{ secrets.SPONTE_PASSWORD }}

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar ChromeDriver compatível
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: latest

      - name: Verificar versões
        run: |
          google-chrome --version
          chromedriver --version

      - name: Executar script Python do Geração Tech
        run: python main_gt.py
